title: Sam Collier
description: Sam Collier's Portfolio and Blog
baseurl: ""
url: "http://localhost:4000"
collections:
  portfolio:
    output: true
    permalink: /portfolio/:name
exclude:
  - docker-compose.yml
