title: Sam Collier
description: Sam Collier's Portfolio and Blog
baseurl: ""
url: "https://samcollier.dev"
collections:
  portfolio:
    output: true
    permalink: /portfolio/:name
exclude:
  - docker-compose.yml
